# Generated by Django 4.1.7 on 2023-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famille', '0003_activite_contenu_activite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre_interet',
            name='contenu',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='centre_interet',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/centre_interet'),
        ),
    ]
