# Generated by Django 4.1.7 on 2023-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famille', '0004_centre_interet_contenu_centre_interet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/activité'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/actualité'),
        ),
        migrations.AlterField(
            model_name='centre_interet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/centre_interet'),
        ),
    ]
