# Generated by Django 4.2.3 on 2023-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100000)),
                ('number_pharmacy', models.CharField(max_length=25)),
                ('on_call_period', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('Pharmacist_holder', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
