# Generated by Django 4.1.7 on 2023-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=1000)),
                ('numero_pharmacie', models.CharField(max_length=200)),
                ('period_garde', models.CharField(max_length=100)),
                ('date_debut', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField(auto_now=True)),
                ('Pharmacien_tituleur', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/pharmacie')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
