# Generated by Django 4.1.7 on 2023-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='date_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/pharmacie'),
            preserve_default=False,
        ),
    ]
