# Generated by Django 4.1.7 on 2023-08-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_alter_pharmacie_date_debut_alter_pharmacie_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='localisation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
