# Generated by Django 4.1.7 on 2023-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_alter_pharmacie_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='position_map',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='localisation',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
