# Generated by Django 4.1.7 on 2023-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('initiateur', models.CharField(choices=[('mairie', 'MAIRIE'), ('commune', 'COMMUNE'), ('état', 'ETAT')], max_length=20)),
                ('type_project', models.CharField(choices=[('sanitaire', 'MAIRIE'), ('anenagement', 'COMMUNE'), ('routiere', 'Routiere'), ('social', 'Social'), ('educative', 'Educative')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/project')),
            ],
        ),
    ]
