# Generated by Django 4.2.3 on 2023-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000000)),
            ],
        ),
    ]
