# Generated by Django 4.1.7 on 2023-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre_sante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/centre_sante'),
        ),
    ]
