# Generated by Django 4.2.3 on 2023-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_center',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/centre_sante'),
        ),
    ]
