# Generated by Django 4.2.3 on 2023-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_actor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/user'),
        ),
    ]
