# Generated by Django 4.2.3 on 2023-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin'), ('personnalisé', 'Personnalisé')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('way_of_birth', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin'), ('personnalisé', 'Personnalisé')], max_length=255)),
                ('name_of_father', models.CharField(max_length=255)),
                ('name_of_mother', models.CharField(max_length=255)),
            ],
        ),
    ]
