# Generated by Django 4.1.7 on 2023-08-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('famille', '0004_centre_interet_contenu_centre_interet_image'),
        ('centre_sante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=20)),
                ('date_de_naissance', models.DateField()),
                ('lieu_dela_naissance', models.CharField(choices=[('hopital', 'Hopital'), ('a domicile', 'A domicile')], max_length=255)),
                ('nom_du_pere', models.CharField(max_length=255)),
                ('nom_dela_mere', models.CharField(max_length=255)),
                ('lieu_habitation', models.CharField(blank=True, max_length=500, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='famille.famille')),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre_sante.centre_sante')),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=20)),
                ('fonction', models.CharField(max_length=255)),
                ('date_de_naissance', models.DateField()),
                ('date_de_deces', models.DateField()),
                ('lieu_ode_deces', models.CharField(choices=[('hopital', 'Hopital'), ('a domicile', 'A domicile')], max_length=255)),
                ('raison_du_deces', models.CharField(max_length=100000)),
                ('nom_du_pere', models.CharField(max_length=255)),
                ('nom_de_mere', models.CharField(max_length=255)),
                ('lieu_habitation', models.CharField(blank=True, max_length=500, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='famille.famille')),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre_sante.centre_sante')),
            ],
        ),
    ]
