# Generated by Django 4.2.3 on 2023-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_de_vie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='dwelling_place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='birth',
            name='way_of_birth',
            field=models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=255),
        ),
    ]
