# Generated by Django 4.2.3 on 2023-07-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_de_vie', '0002_birth_dwelling_place_alter_birth_way_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin'), ('personnalisé', 'Personnalisé')], max_length=20)),
                ('function', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('way_of_birth', models.CharField(choices=[('hopital', 'Hopital'), ('a domicile', 'A domicile')], max_length=255)),
                ('reason_of_death', models.CharField(max_length=100000)),
                ('name_of_father', models.CharField(max_length=255)),
                ('name_of_mother', models.CharField(max_length=255)),
                ('dwelling_place', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
