# Generated by Django 4.1.7 on 2023-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demande_emploie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau_etude', models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('primaire', 'Primaire'), ('secndaire', 'Secondaire'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20, null=True)),
                ('dernier_diplome', models.CharField(blank=True, choices=[('aucun', 'AUCUN'), ('cep', 'CEP'), ('primaire', 'BEPC'), ('secndaire', 'BAC'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20, null=True)),
                ('domaine', models.CharField(blank=True, max_length=255, null=True)),
                ('competence', models.CharField(blank=True, max_length=1000, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('metier', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/demande_emploie')),
                ('contenu', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
