# Generated by Django 4.1.7 on 2023-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_emploie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_emploie',
            name='domaine',
        ),
        migrations.AddField(
            model_name='demande_emploie',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
