# Generated by Django 4.2.3 on 2023-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_emploie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_emploie',
            name='dernier_diplome',
            field=models.CharField(choices=[('aucun', 'AUCUN'), ('cep', 'CEP'), ('primaire', 'BEPC'), ('secndaire', 'BAC'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20),
        ),
        migrations.AlterField(
            model_name='demande_emploie',
            name='niveau_etude',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('primaire', 'Primaire'), ('secndaire', 'Secondaire'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20),
        ),
    ]
