# Generated by Django 4.2.3 on 2023-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_emploie', '0002_alter_demande_emploie_dernier_diplome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_emploie',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demande_emploie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='demande_emploie',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demande_emploie',
            name='skill',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='demande_emploie',
            name='dernier_diplome',
            field=models.CharField(blank=True, choices=[('aucun', 'AUCUN'), ('cep', 'CEP'), ('primaire', 'BEPC'), ('secndaire', 'BAC'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demande_emploie',
            name='domaine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demande_emploie',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demande_emploie',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demande_emploie',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('primaire', 'Primaire'), ('secndaire', 'Secondaire'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20, null=True),
        ),
    ]
