# Generated by Django 4.2.4 on 2023-08-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_emploie', '0002_remove_demande_emploie_domaine_demande_emploie_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre_emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_du_poste', models.CharField(max_length=255)),
                ('deescription', models.CharField(max_length=255)),
                ('diplome_requis', models.CharField(choices=[('aucun', 'AUCUN'), ('cep', 'CEP'), ('primaire', 'BEPC'), ('secndaire', 'BAC'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('licence', 'Licence'), ('maitrise', 'Maitrise'), ('master', 'Master')], default='aucun', max_length=20)),
                ('employeur', models.CharField(max_length=255)),
                ('type_de_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], default='CDD', max_length=20)),
                ('lieu', models.CharField(max_length=255)),
                ('competence_requis', models.CharField(max_length=500)),
                ('salaire', models.CharField(max_length=1000)),
                ('date_de_publication', models.DateField()),
                ('date_limite', models.DateField()),
            ],
        ),
    ]
