# Generated by Django 4.2.3 on 2023-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_emploie', '0003_demande_emploie_content_demande_emploie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_emploie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/demande_emploie'),
        ),
    ]
