# Generated by Django 4.2.3 on 2023-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_project', models.CharField(choices=[('mairie', 'MAIRIE'), ('commune', 'COMMUNE'), ('état', 'ETAT')], max_length=255)),
                ('type_project', models.CharField(choices=[('sanitaire', 'MAIRIE'), ('anenagement', 'COMMUNE'), ('routiere', 'Routiere'), ('social', 'Social'), ('educative', 'Educative')], max_length=255)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
