# Generated by Django 4.2.3 on 2023-07-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('metier', '0002_job_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='skill.skill'),
        ),
    ]
