# Generated by Django 4.2.3 on 2023-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=20)),
                ('function', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('Type_of_accommodation_on_arrival', models.CharField(choices=[('chez un parent', 'Chez un parent'), ('nouvelle habitation', 'Nouvelle habitation')], max_length=255)),
                ('origin', models.CharField(max_length=100000)),
                ('name_of_father', models.CharField(max_length=255)),
                ('name_of_mother', models.CharField(max_length=255)),
                ('dwelling_place', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
