# Generated by Django 4.1.7 on 2023-08-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('famille', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denemager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=20)),
                ('fonction', models.CharField(max_length=255)),
                ('lieu_habitation', models.CharField(max_length=1000)),
                ('date_de_naissance', models.DateField()),
                ('nouvelle_destination', models.CharField(blank=True, max_length=2000, null=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famille.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Anemager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=20)),
                ('fonction', models.CharField(max_length=255)),
                ('date_de_naissance', models.DateField()),
                ('Type_of_accommodation_on_arrival', models.CharField(choices=[('chez un parent', 'Chez un parent'), ('nouvelle habitation', 'Nouvelle habitation')], max_length=255)),
                ('origine', models.CharField(max_length=100000)),
                ('nom_du_pere', models.CharField(max_length=255)),
                ('nom_de_mere', models.CharField(max_length=255)),
                ('lieu_habitation', models.CharField(blank=True, max_length=500, null=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famille.famille')),
            ],
        ),
    ]
