# Generated by Django 4.1.7 on 2023-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anemager',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='denemager',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
