# Generated by Django 4.2.4 on 2023-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0002_anemager_status_denemager_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anemager',
            name='annule',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='amenagement annullée'),
        ),
    ]
