# Generated by Django 4.1.7 on 2023-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epidemie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=1000)),
                ('traitements', models.CharField(max_length=100)),
                ('date_debut', models.DateField(auto_now=True)),
                ('date_fin', models.DateField(auto_now=True)),
                ('nombre_cas', models.CharField(max_length=100)),
                ('nombre_mort', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=1000)),
                ('traitements', models.CharField(max_length=100)),
            ],
        ),
    ]
