# Generated by Django 4.2.4 on 2023-09-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0002_maladie_famille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maladie',
            old_name='famille',
            new_name='Epidemie',
        ),
    ]
