# Generated by Django 4.1.7 on 2023-08-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitant',
            name='genre',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=255, null=True),
        ),
    ]
