# Generated by Django 4.2.4 on 2023-09-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0001_initial'),
        ('maladies', '0001_initial'),
        ('compte', '0002_habitant_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitant',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='habitant',
            name='maladie',
        ),
        migrations.AddField(
            model_name='habitant',
            name='competence',
            field=models.ManyToManyField(blank=True, null=True, related_name='competence', to='competence.competence'),
        ),
        migrations.AddField(
            model_name='habitant',
            name='maladie',
            field=models.ManyToManyField(blank=True, null=True, related_name='maladies', to='maladies.maladie'),
        ),
    ]
