# Generated by Django 4.2.4 on 2023-09-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_pharmacie_position_map_alter_pharmacie_localisation'),
        ('centre_sante', '0002_alter_centre_sante_image'),
        ('compte', '0003_remove_habitant_competence_remove_habitant_maladie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitant',
            name='centre_sante',
            field=models.ManyToManyField(blank=True, null=True, related_name='competence', to='centre_sante.centre_sante'),
        ),
        migrations.AddField(
            model_name='habitant',
            name='pharmacie',
            field=models.ManyToManyField(blank=True, null=True, related_name='maladies', to='pharmacie.pharmacie'),
        ),
    ]
