# Generated by Django 4.2.4 on 2023-09-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0002_anemager_status_denemager_status'),
        ('compte', '0004_habitant_centre_sante_habitant_pharmacie'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitant',
            name='amenager',
            field=models.ManyToManyField(blank=True, null=True, related_name='amenager', to='deplacement.anemager'),
        ),
        migrations.AddField(
            model_name='habitant',
            name='demenager',
            field=models.ManyToManyField(blank=True, null=True, related_name='demenager', to='deplacement.denemager'),
        ),
    ]
